openapi: 3.0.3
info:
  title: Warehouse Operations API
  description: |
    API for managing the physical fulfillment workflow within the warehouse. 
    This includes orchestrating work via waves, managing pick lists, and confirming packages.
  version: 1.0.0
servers:
  - url: https://api.example.com/fulfillment/warehouse_ops/v1
paths:
  /waves/{wave_id}/release:
    post:
      summary: Release a Planned Wave
      description: |
        Allows a Warehouse Manager to release a planned wave, which triggers the creation and assignment of pick lists to operators. 
        This corresponds to the user story WO-08.
      operationId: release_wave
      parameters:
        - name: wave_id
          in: path
          required: true
          description: The unique identifier for the wave to be released.
          schema:
            type: string
            format: uuid
      responses:
        '202':
          description: Accepted. The wave has been successfully released and work is being dispatched to the floor.
        '400':
          description: Bad Request. The wave is not in a 'Planned' state and cannot be released.
        '404':
          description: Not Found. No wave found with the given ID.
  /pick_lists/{pick_list_id}/items/confirm_pick:
    post:
      summary: Confirm an Item Pick
      description: |
        Allows a Picker, typically via a handheld scanner, to confirm that a specific item on a pick list has been successfully picked.
        This corresponds to the user story WO-11.
      operationId: confirm_item_pick
      parameters:
        - name: pick_list_id
          in: path
          required: true
          description: The unique identifier for the pick list being worked on.
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmPickRequest'
      responses:
        '200':
          description: OK. The pick has been successfully recorded.
        '400':
          description: Bad Request. The provided item is not on the pick list or the quantity is incorrect.
        '404':
          description: Not Found. No pick list found with the given ID.

components:
  schemas:
    ConfirmPickRequest:
      type: object
      required:
        - sku
        - quantity_picked
        - bin_location_scanned
      properties:
        sku:
          type: string
          description: The SKU of the item that was scanned and picked.
        quantity_picked:
          type: integer
          description: The quantity of the SKU that was picked.
        bin_location_scanned:
          type: string
          description: The identifier of the physical bin location that was scanned.
    
    Wave:
      type: object
      properties:
        wave_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [planned, released, closed]
        release_strategy:
          type: string
          example: "wave_strategy"
        created_at:
          type: string
          format: date-time
        released_at:
          type: string
          format: date-time

    PickList:
      type: object
      properties:
        pick_list_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, in_progress, completed]
        picker_id:
          type: string
        instructions:
          type: array
          items:
            $ref: '#/components/schemas/PickInstruction'

    PickInstruction:
      type: object
      properties:
        sequence:
          type: integer
        sku:
          type: string
        quantity_to_pick:
          type: integer
        bin_location:
          type: string