name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Run Tests
      run: mvn test
    
    - name: Build Docker Image
      run: docker build -t paklog-warehouse-operations .
    
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker Image
      run: |
        docker tag paklog-warehouse-operations ${{ secrets.DOCKER_USERNAME }}/paklog-warehouse-operations:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/paklog-warehouse-operations:${{ github.sha }}